### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by AsVHEn** [adwylie/deadbeef-playcount#1]
Hi, first, thank you so much for doing this, I come from foobar2000 and I wanted something like that. So... I would like to know if it could be possible to add one feature:
Wait until x time or percent of song to update count play. Because now, if you skip tracks forward or backward, it add count.
Thank you.

**Comment by adwylie** [comment]
Hey thanks for the feedback. The method you mention was planned, however it's quite difficult to implement (increment wrt/ percentage of song played).

I believe the issue you're seeing is actually a regression from the previous DeaDBeef release 0.7.2 to its current version (1.8.2). The play count should only be incremented when the song finishes through regular playback. I believe the regression also stops the play count from being saved to the audio file. I'm planning to look into this issue over the next few weeks.

If you could confirm the version of DeaDBeef you're using that'd be much appreciated (and try the plugin on 0.7.2 instead).

Also, if this regression is fixed would you still want this alternate play count strategy implemented?

**Comment by AsVHEn** [comment]
Ah ok, it's a "feature" from last Deadbeef version :P.  I hope you can fix it easily.
I am using 1.8.2 on Debian 10.
Percent was only the way foobar2000's plugins avoided problem, not a lack on yours :sweat_smile: .
(Only other things is tag name, because my tags are "PLAY_COUNTER" instead of "play_count" , but it seems yours is more extended, and I can edit anyway :wink:  )

**Comment by adwylie** [comment]
Updated the code to work with DeaDBeeF 1.8.2. Song play count will now only increment when playback completes.

The tag will not be changed from `%play_count%`, since this matches how the feature is used in both foobar2000 and DeaDBeeF (see their 'Title formatting 2.0' wiki entry).

**Comment by AsVHEn** [comment]
I have tried and it works. Nice.


> Updated the code to work with DeaDBeeF 1.8.2. Song play count will now only increment when playback completes.
> 
> The tag will not be changed from `%play_count%`, since this matches how the feature is used in both foobar2000 and DeaDBeeF (see their 'Title formatting 2.0' wiki entry).
